# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build Windows
      working-directory: keyvaultcertdownloader
      run: GOOS=windows CGO_ENABLED=0 go build

    - name: Build Linux
      working-directory: keyvaultcertdownloader
      run: GOOS=linux CGO_ENABLED=0 go build

    - name: Getting tool version
      working-directory: keyvaultcertdownloader
      run: |
        echo "TOOL_VERSION=$(cat ./keyvaultcertdownloader.go | grep version | grep "= \"" | awk -F= '{print $2}' | tr -d " " | tr -d "\"")" >> $GITHUB_ENV
    
    - name: Tool Version
      run: |
        echo "tool version is: ${{ env.TOOL_VERSION }}"

    - name: Display directory structure
      run: |
        tree
        pwd
        ls -al



